name = "InstrumentConfig"
uuid = "2ae464b0-21de-4247-9233-e7c17725eb53"
authors = ["Esti Gajda", "Morten F. Rasmussen <10264458+mofii@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
